# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'
inhibit_all_warnings!

use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true, :deterministic_uuids => false

target 'Sauap' do
  pod 'Alamofire', '5.4.4'
  pod 'SDWebImage'
  pod 'Firebase'
  # Pods for Sauap

  target 'SauapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SauapUITests' do
    # Pods for testing
  end

end
